apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: acc-api
  name: acc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: acc-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: acc-api
    spec:
      containers:
        - args:
            - serve
          env:
            - name: ACC_API_PORT
          image: f5devcentral/f5-automation-config-converter:1.18.0
          name: acc-api
          ports:
            - containerPort: 8080
              hostIP: 127.0.0.1
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: acc-api-tmpfs0
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: acc-api-tmpfs0
status: {}
