apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: journeys
  name: journeys
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: journeys
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: journeys
    spec:
      containers:
        - args:
            - runserver
          env:
            - name: ACC_API_HOST
              value: acc-api
            - name: ACC_API_PORT
            - name: BROKER_URL
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASS
            - name: DB_PORT
            - name: DB_USER
            - name: JOURNEYS_PORT
            - name: MIGRATE_DIR
          image: f5devcentral/f5-bigip-journeys-app:v3.2.4
          name: journeys
          ports:
            - containerPort: 443
              hostIP: 127.0.0.1
          resources: {}
      restartPolicy: Always
status: {}
